version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: greencitydb
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: ./GreenCity-App-Backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/greencitydb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: dbadmin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./GreenCity-App-Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  dbdata:
