version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: greencitydb
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    image: app_backend:latest
    container_name: frontend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/greencitydb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: dbadmin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: app_frontend:latest
    ports:
      - "3000:3000"

volumes:
  dbdata:


